# Generated by Django 5.2.1 on 2025-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyEmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('email_username', models.CharField(max_length=255)),
                ('email_password', models.CharField(max_length=255)),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('imap_server', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_limit', models.PositiveIntegerField(default=100)),
                ('daily_sent', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DummyEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=1000)),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
