# Generated by Django 5.2.1 on 2025-05-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=50)),
                ('checked_at', models.DateTimeField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('email_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dummyemailconfiguration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
